/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mbari.mondrian;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SanityTest {
    @Test void appHasAGreeting() {
        assertTrue(true);
    }
}
