/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mbari.mondrian;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import org.mbari.imgfx.etc.rx.events.Event;
import org.mbari.mondrian.javafx.AnnotationPaneController;
import org.mbari.mondrian.msg.messages.SetSelectedImage;


public class App extends Application {

    private static final System.Logger log = System.getLogger(App.class.getSimpleName());
    private final ToolBox toolbox = Initializer.getToolBox();
    private final AppController appController = new AppController(toolbox);

    @Override
    public void start(Stage stage) throws Exception {
        var paneController = new AnnotationPaneController(toolbox);

        toolbox.data()
                .selectedImageProperty()
                .addListener((obs, oldv, newv) -> {
                    var image = newv == null ? null : new Image(newv.getUrl().toExternalForm());
                    paneController.getAutoscalePaneController()
                            .getView()
                            .setImage(image);
                });

        // TODO HAck for development
        var imageUrl = getClass().getResource("/20220828T160015Z--2efffc23-efd3-4fe7-af45-ce2076bb33ca.png");
        var image = new org.mbari.vars.services.model.Image();
        image.setUrl(imageUrl);
        toolbox.eventBus().publish(new SetSelectedImage(image));


        toolbox.eventBus()
                .toObserverable()
                .ofType(Event.class)
                .subscribe(event -> log.log(System.Logger.Level.INFO, event));

        var scene = new Scene(paneController.getPane(), 640, 480);
        stage.setScene(scene);
        stage.show();

    }



    public static void main(String[] args) {
        launch(args);
    }
}